package com.lucance.boot.backend.entity;

import jakarta.persistence.*;
import lombok.Data;

import java.math.BigDecimal;
import java.time.OffsetDateTime;

/**
 * Signal entity for trading signals generated by Chan Theory analysis.
 */
@Data
@Entity
@Table(name = "signals")
public class Signal {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "strategy_id")
    private Long strategyId;

    @Column(nullable = false, length = 20)
    private String symbol;

    @Column(nullable = false, length = 10)
    private String interval;

    /**
     * Signal type: "buy" or "sell"
     */
    @Column(name = "signal_type", nullable = false, length = 10)
    private String signalType;

    /**
     * Trading point level: 1, 2, or 3
     */
    @Column(nullable = false)
    private Integer level;

    /**
     * Suggested entry price
     */
    @Column(name = "entry_price", precision = 20, scale = 8)
    private BigDecimal entryPrice;

    /**
     * Stop loss price
     */
    @Column(name = "stop_loss", precision = 20, scale = 8)
    private BigDecimal stopLoss;

    /**
     * Take profit price
     */
    @Column(name = "take_profit", precision = 20, scale = 8)
    private BigDecimal takeProfit;

    /**
     * Confidence level: "high", "medium", or "low"
     */
    @Column(nullable = false, length = 10)
    private String confidence;

    /**
     * Reason for the signal
     */
    @Column(columnDefinition = "TEXT")
    private String reason;

    /**
     * Related fenxing ID
     */
    @Column(name = "fenxing_id")
    private Long fenxingId;

    /**
     * Related bi ID
     */
    @Column(name = "bi_id")
    private Long biId;

    /**
     * Related xianduan ID
     */
    @Column(name = "xianduan_id")
    private Long xianduanId;

    /**
     * Related zhongshu ID
     */
    @Column(name = "zhongshu_id")
    private Long zhongshuId;

    /**
     * Status: pending, confirmed, executed, cancelled, expired
     */
    @Column(length = 20)
    private String status = "pending";

    @Column(name = "created_at")
    private OffsetDateTime createdAt;

    @Column(name = "updated_at")
    private OffsetDateTime updatedAt;

    @PrePersist
    protected void onCreate() {
        createdAt = OffsetDateTime.now();
        updatedAt = OffsetDateTime.now();
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = OffsetDateTime.now();
    }
}
